const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const time=ms=>ms?new Date(ms).toLocaleTimeString([], {hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
const fmt=n=>Number.isFinite(n)?Number(n).toFixed(1):'—';
const pct=n=>Number.isFinite(n)?`${Math.round(n*100)}%`:'—';

function channelOptions(current){return ['sweep',...Array.from({length:79},(_,i)=>String(i))].map(value=>`<option value="${value}" ${String(current)===value?'selected':''}>${value==='sweep'?'SWEEP 0–78':`CH ${value} · ${2402+Number(value)} MHz`}</option>`).join('');}
function metric(label,value){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function rows(list,selected){return list.map(o=>`<tr class="clickable ${String(selected)===o.lapHex?'selected':''}" data-classic-lap="${esc(o.lapHex)}"><td><code>${esc(o.lapHex)}</code></td><td><code>${o.selectedUap===null?'—':`0x${o.selectedUap.toString(16).padStart(2,'0').toUpperCase()}`}</code></td><td>${o.selectedUap===null?'CANDIDATE':pct(o.uapConfidence)}</td><td>${o.packetCount}</td><td>${o.headerPacketCount}</td><td>${esc(o.channels.join(', '))}</td><td>${fmt(o.averageRssi)}</td><td>${o.peakRssi??'—'}</td><td>${esc(o.topPacketTypes.map(x=>`${x.name} (${x.count})`).join(', ')||'—')}</td><td>${time(o.lastSeen)}</td></tr>`).join('')||'<tr><td colspan="10"><div class="empty-state compact"><strong>NO CLASSIC ACCESS CODES OBSERVED</strong><span>Start Classic observation or use Simulation.</span></div></td></tr>';}

export function renderClassic(s){
  const connected=Boolean(s.transport?.connected);const obs=s.classicObservations??[];const selected=obs.find(o=>o.lapHex===s.selectedClassicLap)??obs[0]??null;const decoder=s.classicDecoder??{};
  const engine=decoder.status==='wasm-worker-ready'?'WASM WORKER':decoder.status==='javascript-fallback'?'JAVASCRIPT FALLBACK':String(decoder.status??'NOT INITIALIZED').toUpperCase();
  return `<div class="page-header"><div><div class="eyebrow">BLUETOOTH CLASSIC · PASSIVE</div><h1>Classic Observation</h1><p>Basic Rate access-code discovery and piconet evidence using the Ubertooth RX_SYMBOLS bulk path. LAP observations are captured facts; UAP/header values remain decoded candidates until repeated evidence stabilizes them.</p></div><div class="page-actions"><button class="btn primary" data-action="start-classic" ${!connected?'disabled':''}>START CLASSIC</button><button class="btn" data-action="stop-stream" ${!s.streaming?'disabled':''}>STOP</button><button class="btn" data-action="classic-clear" ${!obs.length?'disabled':''}>CLEAR ANALYSIS</button></div></div>
  <section class="panel"><div class="panel-title"><span>OBSERVATION CONFIGURATION</span><span>RX ONLY</span></div><div class="control-strip">
    <label>CHANNEL<select data-pref="classicChannel">${channelOptions(s.prefs.classicChannel??'sweep')}</select></label>
    <label>KNOWN LAP<input data-pref="classicKnownLap" value="${esc(s.prefs.classicKnownLap??'')}" placeholder="optional · 9E8B33" maxlength="8"></label>
    <label>MAX AC ERRORS<select data-pref="classicMaxErrors">${[0,1,2,3,4].map(n=>`<option value="${n}" ${Number(s.prefs.classicMaxErrors)===n?'selected':''}>${n}</option>`).join('')}</select></label>
  </div><div class="audit-note">Unknown-LAP discovery in the browser kernel is deliberately exact-match only. When a known LAP is supplied, the access-code matcher accepts the selected 0–4 Hamming errors. This is a narrow libbtbb-derived decoder boundary, not a claim of complete libbtbb parity.</div></section>
  <div class="metric-grid">${metric('LAPs',String(obs.length))}${metric('BR PACKETS',String(s.recorder.packets.toArray().filter(p=>p.classic).length))}${metric('DECODER',engine)}${metric('KERNEL','libbtbb subset')}${metric('MASTER CLOCK','NOT RECOVERED')}${metric('CLASSIC PCAP','UNAVAILABLE')}</div>
  <section class="panel"><div class="panel-title"><span>PICONET CANDIDATES</span><span>OBSERVED / DECODED</span></div><div class="table-wrap"><table><thead><tr><th>LAP</th><th>UAP</th><th>CONF.</th><th>PKTS</th><th>HDR</th><th>CHANNELS</th><th>AVG RSSI</th><th>PEAK</th><th>PACKET TYPES</th><th>LAST</th></tr></thead><tbody>${rows(obs,s.selectedClassicLap)}</tbody></table></div></section>
  ${selected?detail(selected):'<section class="panel"><div class="empty-state"><strong>SELECT A LAP</strong><span>Observed Classic piconet candidates will appear here.</span></div></section>'}
  <details class="panel disclosure"><summary><span>Decoder boundary</span><em>${engine} · libbtbb subset</em></summary><div class="disclosure-body flush"><div class="status-list"><div class="status-row"><span class="lamp ok"></span><strong>JavaScript framing</strong><span>64-byte Ubertooth packet + 50-byte / 400-symbol unpacking</span></div><div class="status-row"><span class="lamp ${decoder.status==='wasm-worker-ready'?'ok':'warning'}"></span><strong>WebAssembly worker</strong><span>Access code, header screen, 64 clock-six/UAP/header candidates</span></div><div class="status-row"><span class="lamp off"></span><strong>Full libbtbb</strong><span>Not embedded; deeper hopping/master-clock algorithms remain a later expansion</span></div></div>${decoder.lastError?`<div class="alert warning"><strong>WASM FALLBACK ACTIVE</strong><span>${esc(decoder.lastError)}</span></div>`:''}<div class="audit-note">The included kernel is algorithmically derived from GPL-2.0 libbtbb source and ships with attribution/source in <code>third_party/libbtbb-wasm/</code>. It runs off the main UI thread when Web Workers and WebAssembly are available.</div></div></details>`;
}

function detail(o){
  const candidates=(o.rankedUaps??[]).slice(0,5).map((x,i)=>`<tr><td>${i+1}</td><td><code>${esc(x.uapHex)}</code></td><td>${x.count}</td><td>${pct(x.confidence)}</td></tr>`).join('')||'<tr><td colspan="4">No repeated header candidates yet.</td></tr>';
  return `<section class="panel classic-detail"><div class="panel-title"><span>SELECTED LAP ${esc(o.lapHex)}</span><span>${o.selectedUap===null?'UAP CANDIDATE':'UAP STABILIZED'}</span></div><div class="detail-grid"><div class="kv-stack"><div class="kv"><span>First seen</span><strong>${time(o.firstSeen)}</strong></div><div class="kv"><span>Last seen</span><strong>${time(o.lastSeen)}</strong></div><div class="kv"><span>Packets</span><strong>${o.packetCount}</strong></div><div class="kv"><span>Minimum AC errors</span><strong>${o.minAcErrors??'—'}</strong></div></div><div class="kv-stack"><div class="kv"><span>UAP candidate</span><strong>${o.selectedUap===null?'—':`0x${o.selectedUap.toString(16).padStart(2,'0').toUpperCase()}`}</strong></div><div class="kv"><span>UAP confidence</span><strong>${pct(o.uapConfidence)}</strong></div><div class="kv"><span>Clock-six candidate</span><strong>${o.selectedHeader?.clock6??'—'}</strong></div><div class="kv"><span>LT_ADDR</span><strong>${o.selectedHeader?.ltAddr??'—'}</strong></div></div><div class="kv-stack"><div class="kv"><span>Decoded type</span><strong>${esc(o.selectedHeader?.typeName??'—')}</strong></div><div class="kv"><span>Header flags</span><strong>${o.selectedHeader?.flags??'—'}</strong></div><div class="kv"><span>Channels observed</span><strong>${esc(o.channels.join(', ')||'—')}</strong></div><div class="kv"><span>Evidence quality</span><strong>${esc(o.evidence)}</strong></div></div></div><div class="panel-title subhead"><span>TOP UAP CANDIDATES</span><span>STABILIZES AFTER ≥3 MATCHING HEADERS</span></div><div class="table-wrap"><table><thead><tr><th>RANK</th><th>UAP</th><th>MATCHES</th><th>CONFIDENCE</th></tr></thead><tbody>${candidates}</tbody></table></div><div class="button-row"><button class="btn" data-action="classic-use-selected-lap">USE AS KNOWN LAP</button><button class="btn" data-action="classic-show-packets">SHOW LAP PACKETS</button></div><div class="audit-note">A stable UAP candidate requires at least three repeated matching header results with ≥60% confidence; it is still a decoder result, not a Bluetooth identity claim. Full 27-bit master clock recovery and hop following are intentionally not asserted in this release.</div></section>`;
}
