import { compareSurveyStations } from '../survey/survey.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const fmt=v=>Number.isFinite(v)?Number(v).toFixed(1):'—';
const fmtTime=ms=>ms?new Date(ms).toLocaleString():'—';

function metric(label,value){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}

export function renderSurvey(s) {
  const projects=s.surveyProjects??[];
  const active=projects.find(p=>p.id===s.prefs.surveyActiveProjectId)??projects[0]??null;
  const stations=active?.stations??[];
  const a=stations.find(x=>x.id===s.prefs.surveyCompareA)??stations[0]??null;
  const b=stations.find(x=>x.id===s.prefs.surveyCompareB)??stations[1]??null;
  const comparison=compareSurveyStations(a,b);
  const run=s.surveyRun??{active:false};
  const connected=Boolean(s.transport?.connected);
  const duration=Math.max(5,Number(s.prefs.surveySampleSeconds??30));
  const elapsed=run.active?Math.max(0,Date.now()-(run.phaseStartedAt??Date.now())):0;
  const remaining=run.active?Math.max(0,(run.phaseDurationMs??duration*1000)-elapsed):0;
  const progress=run.active?Math.min(100,elapsed/Math.max(1,run.phaseDurationMs??1)*100):0;
  return `<div class="page-header"><div><div class="eyebrow">RF SURVEY</div><h1>Environmental Survey Workbench</h1><p>Measure named locations sequentially, compare radio environments, and preserve the evidence behind every station fingerprint.</p></div><div class="page-actions"><button class="btn primary" data-action="survey-start" ${!connected||!active||run.active?'disabled':''}>START STATION</button><button class="btn danger" data-action="survey-cancel" ${!run.active?'disabled':''}>CANCEL</button></div></div>
  <section class="panel survey-sequence"><div class="panel-title"><span>MEASUREMENT SEQUENCE</span><span>ONE UBERTOOTH · TWO PHASES</span></div><div class="survey-flow"><span>SPECTRUM SAMPLE</span><b>→</b><span>BLE SAMPLE</span><b>→</b><span>SAVE STATION</span></div><div class="audit-note">Ubertooth does not run SPECAN and BLE acquisition simultaneously. A station is deliberately measured in two consecutive phases of equal duration. Comparisons preserve that acquisition order instead of presenting the datasets as simultaneous. The BLE phase uses the selected advertising channel (37, 38, or 39); station channel statistics report only packets actually observed.</div></section>
  <div class="instrument-grid cols-2"><section class="panel"><div class="panel-title"><span>SURVEY PROJECT</span><span>${projects.length} LOCAL</span></div><div class="form-grid"><label>ACTIVE PROJECT<select data-pref="surveyActiveProjectId"><option value="">— Select —</option>${projects.map(p=>`<option value="${esc(p.id)}" ${active?.id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>NEW PROJECT NAME<input id="survey-project-name" value="" placeholder="Workshop RF Baseline"></label></div><div class="button-row"><button class="btn" data-action="survey-create">NEW PROJECT</button><button class="btn danger" data-action="survey-delete-project" ${!active||run.active?'disabled':''}>DELETE PROJECT</button><button class="btn" data-action="survey-export-json" ${!active?'disabled':''}>EXPORT JSON</button><button class="btn" data-action="survey-export-csv" ${!active||!stations.length?'disabled':''}>EXPORT CSV</button></div></section>
  <section class="panel"><div class="panel-title"><span>NEXT STATION</span><span>${run.active?esc(String(run.stage??'RUNNING').toUpperCase()):'READY'}</span></div><div class="form-grid three"><label>STATION NAME<input id="survey-station-name" value="${esc(run.stationName??'')}" placeholder="Electronics Bench" ${run.active?'disabled':''}></label><label>PHASE DURATION<select data-pref="surveySampleSeconds" ${run.active?'disabled':''}>${[10,30,60,120].map(n=>`<option value="${n}" ${duration===n?'selected':''}>${n} seconds × 2</option>`).join('')}</select></label><label>BLE ADV CHANNEL<select data-pref="bleFollowChannel" ${run.active?'disabled':''}>${[37,38,39].map(ch=>`<option value="${ch}" ${Number(s.prefs.bleFollowChannel??37)===ch?'selected':''}>${ch}</option>`).join('')}</select></label><label>NOTE<input id="survey-station-note" value="${esc(run.note??'')}" placeholder="Optional context" ${run.active?'disabled':''}></label></div>${run.active?`<div class="survey-progress"><div style="width:${progress.toFixed(1)}%"></div></div><div class="metric-grid embedded">${metric('PHASE',String(run.stage??'').toUpperCase())}${metric('REMAINING',`${(remaining/1000).toFixed(1)} s`)}${metric('TOTAL STATION',`${duration*2} s`)}${metric('CAPTURE',s.recorder.stats().packetsReceived.toLocaleString())}</div>`:'<div class="empty-state compact"><strong>READY TO SAMPLE</strong><span>Name the station, then keep the Ubertooth in the same physical position until both phases complete.</span></div>'}</section></div>
  <section class="panel"><div class="panel-title"><span>MEASUREMENT STATIONS</span><span>${stations.length}</span></div><div class="table-wrap"><table><thead><tr><th>STATION</th><th>TIME</th><th>SPECTRUM MEAN</th><th>STRONGEST</th><th>BLE RATE</th><th>ADVERTISERS</th><th>CONNECTIONS</th><th>BUSIEST CHANNELS</th><th></th></tr></thead><tbody>${stations.map(st=>`<tr><td><strong>${esc(st.name)}</strong><div class="subtle">${esc(st.note||'')}</div></td><td>${esc(fmtTime(st.startedAt))}</td><td>${esc(fmt(st.fingerprint?.spectrumMeanRawRssi))} raw</td><td>${st.fingerprint?.spectrumStrongestMHz??'—'} MHz / ${st.fingerprint?.spectrumStrongestRawRssi??'—'} raw</td><td>${esc(fmt(st.fingerprint?.blePacketRate))} pkt/s</td><td>${st.fingerprint?.advertiserCount??0}</td><td>${st.fingerprint?.connectionCount??0}</td><td>${esc((st.fingerprint?.busiestChannels??[]).map(c=>`CH${c.channel}:${c.packetCount}`).join(' · ')||'—')}</td><td><button class="btn tiny danger" data-survey-station-delete="${esc(st.id)}" ${run.active?'disabled':''}>DELETE</button></td></tr>`).join('')||'<tr><td colspan="9"><div class="empty-state compact">No stations recorded yet.</div></td></tr>'}</tbody></table></div></section>
  <section class="panel"><div class="panel-title"><span>STATION COMPARISON</span><span>ENVIRONMENTAL DIFFERENCE</span></div><div class="filter-strip"><label>FROM<select data-pref="surveyCompareA">${stations.map(st=>`<option value="${esc(st.id)}" ${a?.id===st.id?'selected':''}>${esc(st.name)}</option>`).join('')}</select></label><label>TO<select data-pref="surveyCompareB">${stations.map(st=>`<option value="${esc(st.id)}" ${b?.id===st.id?'selected':''}>${esc(st.name)}</option>`).join('')}</select></label></div>${comparison?comparisonPanel(comparison,a,b):'<div class="empty-state compact"><strong>TWO STATIONS REQUIRED</strong><span>Record at least two locations to compare their RF fingerprints.</span></div>'}</section>
  <div class="note">Survey fingerprints characterize an observed radio environment at a named measurement station. They do not identify people, infer physical ownership of randomized Bluetooth addresses, or claim simultaneous spectrum/BLE measurement.</div>`;
}

function comparisonPanel(c,a,b){
  const deltas=c.channelDeltas.slice(0,8).filter(x=>x.packetDelta!==0);
  return `<div class="survey-compare-head"><strong>${esc(a.name)}</strong><span>→</span><strong>${esc(b.name)}</strong></div><div class="metric-grid">${metric('BLE RATE Δ',`${c.packetRateDelta>=0?'+':''}${c.packetRateDelta.toFixed(1)} pkt/s`)}${metric('ADVERTISERS Δ',`${c.advertiserDelta>=0?'+':''}${c.advertiserDelta}`)}${metric('CONNECTIONS Δ',`${c.connectionDelta>=0?'+':''}${c.connectionDelta}`)}${metric('SPECTRUM MEAN Δ',Number.isFinite(c.spectrumMeanDelta)?`${c.spectrumMeanDelta>=0?'+':''}${c.spectrumMeanDelta.toFixed(1)} raw`:'—')}</div><div class="instrument-grid cols-2 embedded"><div class="kv-stack"><div class="kv"><span>Added observed addresses</span><strong>${esc(c.addedAdvertisers.join(', ')||'None')}</strong></div><div class="kv"><span>Removed observed addresses</span><strong>${esc(c.removedAdvertisers.join(', ')||'None')}</strong></div></div><div class="channel-delta-list">${deltas.map(d=>`<div><strong>CH ${d.channel}</strong><span>${d.packetDelta>=0?'+':''}${d.packetDelta} packets${Number.isFinite(d.peakRssiDelta)?` · peak ${d.peakRssiDelta>=0?'+':''}${d.peakRssiDelta} dB`:''}</span></div>`).join('')||'<div class="empty-state compact">No channel-count differences.</div>'}</div></div>`;
}
